package com.axolync.android.server

import android.content.Context
import android.content.res.AssetManager
import android.util.Log
import fi.iki.elonen.NanoHTTPD
import java.io.IOException

/**
 * LocalHttpServer serves bundled web application assets via HTTP on localhost.
 * Hardened with traversal protection, method restrictions, SPA fallback, and
 * support for extensionless ESM imports generated by TypeScript output.
 */
class LocalHttpServer(
    private val context: Context,
    private val port: Int = 0 // 0 = auto-assign
) : NanoHTTPD("127.0.0.1", port) {

    private data class ResolvedAsset(val requestPath: String, val assetPath: String, val mimeType: String)

    private val assetManager: AssetManager = context.assets
    private val assetBasePath = "axolync-browser"

    companion object {
        private const val TAG = "LocalHttpServer"

        // Supported MIME types (explicit mapping)
        private val MIME_TYPES = mapOf(
            ".html" to "text/html",
            ".js" to "application/javascript",
            ".mjs" to "application/javascript",
            ".css" to "text/css",
            ".json" to "application/json",
            ".map" to "application/json",
            ".svg" to "image/svg+xml",
            ".png" to "image/png",
            ".jpg" to "image/jpeg",
            ".jpeg" to "image/jpeg",
            ".ogg" to "audio/ogg",
            ".mp3" to "audio/mpeg",
            ".wav" to "audio/wav",
            ".lrc" to "text/plain; charset=utf-8",
            ".woff" to "font/woff",
            ".woff2" to "font/woff2",
            ".ttf" to "font/ttf",
            ".wasm" to "application/wasm"
        )
    }

    override fun serve(session: IHTTPSession): Response {
        // Only allow GET and HEAD methods
        if (session.method != Method.GET && session.method != Method.HEAD) {
            Log.w(TAG, "Method not allowed: ${session.method}")
            return newFixedLengthResponse(
                Response.Status.METHOD_NOT_ALLOWED,
                "text/plain",
                "405 Method Not Allowed"
            )
        }

        var uri = session.uri

        // Health check endpoint
        if (uri == "/health") {
            return newFixedLengthResponse(
                Response.Status.OK,
                "application/json",
                "{\"status\":\"ok\",\"server\":\"LocalHttpServer\",\"version\":\"1.0\"}"
            )
        }

        // Normalize URI FIRST, then check for traversal
        uri = normalizeUri(uri) ?: run {
            Log.w(TAG, "Path traversal attempt blocked: ${session.uri}")
            return newFixedLengthResponse(
                Response.Status.FORBIDDEN,
                "text/plain",
                "403 Forbidden"
            )
        }

        // Default to index.html for root
        if (uri == "/" || uri.isEmpty()) {
            uri = "/index.html"
        }

        val resolved = resolveAsset(uri)
        if (resolved != null) {
            if (session.method == Method.HEAD) {
                Log.d(TAG, "HEAD: ${resolved.assetPath} (${resolved.mimeType})")
                val response = newFixedLengthResponse(Response.Status.OK, resolved.mimeType, "")
                response.addHeader("Content-Type", resolved.mimeType)
                return response
            }

            return try {
                val inputStream = assetManager.open(resolved.assetPath)
                Log.d(TAG, "Serving: ${resolved.assetPath} (${resolved.mimeType})")
                newChunkedResponse(Response.Status.OK, resolved.mimeType, inputStream)
            } catch (e: IOException) {
                Log.w(TAG, "Failed to open resolved asset: ${resolved.assetPath}")
                newFixedLengthResponse(Response.Status.NOT_FOUND, "text/plain", "404 Not Found: $uri")
            }
        }

        // SPA fallback for extensionless app routes.
        if (shouldFallbackToIndex(uri)) {
            Log.d(TAG, "SPA fallback: serving index.html for $uri")
            return try {
                if (session.method == Method.HEAD) {
                    val response = newFixedLengthResponse(Response.Status.OK, "text/html", "")
                    response.addHeader("Content-Type", "text/html")
                    response
                } else {
                    val indexStream = assetManager.open("$assetBasePath/index.html")
                    newChunkedResponse(Response.Status.OK, "text/html", indexStream)
                }
            } catch (indexError: IOException) {
                Log.e(TAG, "Failed to serve index.html fallback", indexError)
                newFixedLengthResponse(Response.Status.NOT_FOUND, "text/plain", "404 Not Found: $uri")
            }
        }

        Log.w(TAG, "Asset not found after resolution: $uri")
        return newFixedLengthResponse(Response.Status.NOT_FOUND, "text/plain", "404 Not Found: $uri")
    }

    private fun resolveAsset(uri: String): ResolvedAsset? {
        val candidates = linkedSetOf(uri)
        val lastSegment = uri.substringAfterLast('/')
        val hasExtension = lastSegment.contains('.')

        if (!hasExtension) {
            // TypeScript output in this project uses extensionless ESM imports.
            candidates.add("${uri}.js")
            candidates.add("${uri}.mjs")
            candidates.add("${uri}/index.js")
            candidates.add("${uri}/index.mjs")
            candidates.add("${uri}/index.html")
        }

        for (candidate in candidates) {
            val assetPath = "$assetBasePath$candidate"
            if (assetExists(assetPath)) {
                return ResolvedAsset(candidate, assetPath, getMimeType(candidate))
            }
        }

        return null
    }

    private fun assetExists(assetPath: String): Boolean {
        return try {
            assetManager.open(assetPath).use { /* existence check */ }
            true
        } catch (_: IOException) {
            false
        }
    }

    /**
     * Normalize URI and prevent path traversal attacks.
     * Returns null if traversal attempt detected.
     */
    private fun normalizeUri(uri: String): String? {
        // Decode URI
        val decoded = try {
            java.net.URLDecoder.decode(uri, "UTF-8")
        } catch (e: Exception) {
            return null
        }

        // Normalize multiple slashes to single slash
        val normalized = decoded.replace(Regex("/+"), "/")

        // Reject suspicious patterns after normalization
        if (normalized.contains("..")) {
            return null
        }
        if (normalized.contains("%2e%2e", ignoreCase = true) ||
            normalized.contains("%2f%2e%2e", ignoreCase = true)
        ) {
            return null
        }
        if (normalized.contains("\\")) {
            return null
        }
        if (normalized.contains("\u0000")) {
            return null
        }

        return normalized
    }

    /**
     * Determine if request should fallback to index.html for SPA routing.
     */
    private fun shouldFallbackToIndex(uri: String): Boolean {
        if (uri == "/health") return false
        if (uri.startsWith("/api/")) return false

        // Don't fallback for internal static/module directories.
        if (uri.startsWith("/core/") ||
            uri.startsWith("/ui/") ||
            uri.startsWith("/plugins/") ||
            uri.startsWith("/workers/") ||
            uri.startsWith("/demo/")) {
            return false
        }

        val lastSegment = uri.substringAfterLast('/')
        if (lastSegment.contains('.')) return false

        return true
    }

    private fun getMimeType(uri: String): String {
        val extension = uri.substringAfterLast('.', "")
        return MIME_TYPES[".$extension"] ?: "application/octet-stream"
    }

    fun getServerUrl(): String {
        // Canonical URL uses localhost hostname.
        return "http://localhost:${listeningPort}"
    }

    fun isRunning(): Boolean {
        return isAlive
    }
}
