package com.axolync.android.server

import android.content.Context
import android.content.res.AssetManager
import android.util.Log
import fi.iki.elonen.NanoHTTPD
import java.io.ByteArrayInputStream
import java.io.ByteArrayOutputStream
import java.io.IOException
import java.net.HttpURLConnection
import java.net.URLEncoder
import java.net.URL
import org.json.JSONArray
import org.json.JSONObject
import org.json.JSONTokener

/**
 * LocalHttpServer serves bundled web application assets via HTTP on localhost.
 * Hardened with traversal protection, method restrictions, SPA fallback, and
 * support for extensionless ESM imports generated by TypeScript output.
 */
class LocalHttpServer(
    private val context: Context,
    private val port: Int = 0 // 0 = auto-assign
) : NanoHTTPD("127.0.0.1", port) {

    private data class ResolvedAsset(val requestPath: String, val assetPath: String, val mimeType: String)
    private data class SongIdentity(val artist: String, val title: String)

    private val assetManager: AssetManager = context.assets
    private val assetBasePath = "axolync-browser"

    companion object {
        private const val TAG = "LocalHttpServer"
        private const val BRIDGE_CONFIG_PATH = "/__axolync/runtime-bridge-config"
        private const val BRIDGE_PROXY_PREFIX = "/__axolync/bridge/"
        private const val BRIDGE_DEV_LOG_PATH = "/__axolync/dev-bridge-log"
        private const val BRIDGE_HOST = "localhost"
        private const val SONGSENSE_BACKEND_PORT = 8000
        private const val SYNCENGINE_BACKEND_PORT = 3000
        private const val LYRICFLOW_BACKEND_PORT = 8093
        private const val LRCLIB_GET_URL = "https://lrclib.net/api/get"
        private const val LRCLIB_SEARCH_URL = "https://lrclib.net/api/search"

        // Supported MIME types (explicit mapping)
        private val MIME_TYPES = mapOf(
            ".html" to "text/html",
            ".js" to "application/javascript",
            ".mjs" to "application/javascript",
            ".ts" to "application/javascript",
            ".css" to "text/css",
            ".json" to "application/json",
            ".map" to "application/json",
            ".svg" to "image/svg+xml",
            ".png" to "image/png",
            ".jpg" to "image/jpeg",
            ".jpeg" to "image/jpeg",
            ".ogg" to "audio/ogg",
            ".mp3" to "audio/mpeg",
            ".wav" to "audio/wav",
            ".lrc" to "text/plain; charset=utf-8",
            ".woff" to "font/woff",
            ".woff2" to "font/woff2",
            ".ttf" to "font/ttf",
            ".wasm" to "application/wasm"
        )
    }

    override fun serve(session: IHTTPSession): Response {
        if (session.uri == BRIDGE_CONFIG_PATH && (session.method == Method.GET || session.method == Method.HEAD)) {
            return serveRuntimeBridgeConfig(session)
        }

        if (session.uri == BRIDGE_DEV_LOG_PATH && session.method == Method.POST) {
            return handleBridgeDevLog(session)
        }

        val bridgeKind = resolveBridgeKind(session.uri)
        val bridgeTarget = resolveBridgeTargetUrl(session.uri)
        if (bridgeTarget != null && (session.method == Method.GET || session.method == Method.HEAD || session.method == Method.POST)) {
            return proxyBridgeRequest(session, bridgeTarget, bridgeKind)
        }

        // Only allow GET and HEAD methods
        if (session.method != Method.GET && session.method != Method.HEAD) {
            Log.w(TAG, "Method not allowed: ${session.method}")
            return newFixedLengthResponse(
                Response.Status.METHOD_NOT_ALLOWED,
                "text/plain",
                "405 Method Not Allowed"
            )
        }

        var uri = session.uri

        // Health check endpoint
        if (uri == "/health") {
            return newFixedLengthResponse(
                Response.Status.OK,
                "application/json",
                "{\"status\":\"ok\",\"server\":\"LocalHttpServer\",\"version\":\"1.0\"}"
            )
        }

        // Normalize URI FIRST, then check for traversal
        uri = normalizeUri(uri) ?: run {
            Log.w(TAG, "Path traversal attempt blocked: ${session.uri}")
            return newFixedLengthResponse(
                Response.Status.FORBIDDEN,
                "text/plain",
                "403 Forbidden"
            )
        }

        // Default to index.html for root
        if (uri == "/" || uri.isEmpty()) {
            uri = "/index.html"
        }

        val resolved = resolveAsset(uri)
        if (resolved != null) {
            if (session.method == Method.HEAD) {
                Log.d(TAG, "HEAD: ${resolved.assetPath} (${resolved.mimeType})")
                val response = newFixedLengthResponse(Response.Status.OK, resolved.mimeType, "")
                response.addHeader("Content-Type", resolved.mimeType)
                return response
            }

            return try {
                val inputStream = assetManager.open(resolved.assetPath)
                Log.d(TAG, "Serving: ${resolved.assetPath} (${resolved.mimeType})")
                newChunkedResponse(Response.Status.OK, resolved.mimeType, inputStream)
            } catch (e: IOException) {
                Log.w(TAG, "Failed to open resolved asset: ${resolved.assetPath}")
                newFixedLengthResponse(Response.Status.NOT_FOUND, "text/plain", "404 Not Found: $uri")
            }
        }

        // SPA fallback for extensionless app routes.
        if (shouldFallbackToIndex(uri)) {
            Log.d(TAG, "SPA fallback: serving index.html for $uri")
            return try {
                if (session.method == Method.HEAD) {
                    val response = newFixedLengthResponse(Response.Status.OK, "text/html", "")
                    response.addHeader("Content-Type", "text/html")
                    response
                } else {
                    val indexStream = assetManager.open("$assetBasePath/index.html")
                    newChunkedResponse(Response.Status.OK, "text/html", indexStream)
                }
            } catch (indexError: IOException) {
                Log.e(TAG, "Failed to serve index.html fallback", indexError)
                newFixedLengthResponse(Response.Status.NOT_FOUND, "text/plain", "404 Not Found: $uri")
            }
        }

        Log.w(TAG, "Asset not found after resolution: $uri")
        return newFixedLengthResponse(Response.Status.NOT_FOUND, "text/plain", "404 Not Found: $uri")
    }

    private fun serveRuntimeBridgeConfig(session: IHTTPSession): Response {
        val payload = """
            {
              "host": "localhost",
              "ports": {
                "host": "localhost",
                "browserDevPort": ${listeningPort},
                "desktopDevPort": 4173,
                "songsenseBackendPort": $SONGSENSE_BACKEND_PORT,
                "syncengineBackendPort": $SYNCENGINE_BACKEND_PORT,
                "lyricflowBackendPort": $LYRICFLOW_BACKEND_PORT
              },
              "baseUrls": {
                "songsense": "/__axolync/bridge/songsense/",
                "syncengine": "/__axolync/bridge/syncengine/",
                "lyricflow": "/__axolync/bridge/lyricflow/"
              },
              "backendUrls": {
                "songsense": "http://$BRIDGE_HOST:$SONGSENSE_BACKEND_PORT",
                "syncengine": "http://$BRIDGE_HOST:$SYNCENGINE_BACKEND_PORT",
                "lyricflow": "http://$BRIDGE_HOST:$LYRICFLOW_BACKEND_PORT"
              },
              "devLogEndpoint": "$BRIDGE_DEV_LOG_PATH"
            }
        """.trimIndent()
        val response = if (session.method == Method.HEAD) {
            newFixedLengthResponse(Response.Status.OK, "application/json", "")
        } else {
            newFixedLengthResponse(Response.Status.OK, "application/json", payload)
        }
        response.addHeader("Content-Type", "application/json")
        response.addHeader("Cache-Control", "no-store")
        return response
    }

    private fun handleBridgeDevLog(session: IHTTPSession): Response {
        return try {
            val payload = readRequestBody(session)
            Log.d(TAG, "Bridge dev log payload bytes=${payload.size}")
            newFixedLengthResponse(Response.Status.NO_CONTENT, "text/plain", "")
        } catch (error: Exception) {
            Log.w(TAG, "Failed to record bridge dev log", error)
            newFixedLengthResponse(Response.Status.INTERNAL_ERROR, "text/plain", "500 Failed to record bridge log")
        }
    }

    private fun resolveBridgeKind(uri: String): String? {
        if (!uri.startsWith(BRIDGE_PROXY_PREFIX)) return null
        val remainder = uri.removePrefix(BRIDGE_PROXY_PREFIX)
        val slashIndex = remainder.indexOf('/')
        return if (slashIndex >= 0) remainder.substring(0, slashIndex) else remainder
    }

    private fun resolveBridgeTargetUrl(uri: String): String? {
        val kind = resolveBridgeKind(uri) ?: return null
        val remainder = uri.removePrefix(BRIDGE_PROXY_PREFIX)
        val slashIndex = remainder.indexOf('/')
        val suffix = if (slashIndex >= 0) remainder.substring(slashIndex) else "/"
        val port = when (kind) {
            "songsense" -> SONGSENSE_BACKEND_PORT
            "syncengine" -> SYNCENGINE_BACKEND_PORT
            "lyricflow" -> LYRICFLOW_BACKEND_PORT
            else -> return null
        }
        return "http://$BRIDGE_HOST:$port$suffix"
    }

    private fun proxyBridgeRequest(session: IHTTPSession, targetUrl: String, bridgeKind: String?): Response {
        val requestBody = if (session.method == Method.POST) readRequestBody(session) else ByteArray(0)
        return try {
            val connection = (URL(targetUrl).openConnection() as HttpURLConnection).apply {
                requestMethod = session.method.name
                instanceFollowRedirects = false
                connectTimeout = 3000
                readTimeout = 10_000
                doInput = true
                setRequestProperty("Accept", "application/json")
                setRequestProperty("Cache-Control", "no-store")
                for ((key, value) in session.headers) {
                    if (key.equals("content-length", ignoreCase = true)) continue
                    if (key.equals("host", ignoreCase = true)) continue
                    if (key.equals("connection", ignoreCase = true)) continue
                    setRequestProperty(key, value)
                }
            }

            if (session.method == Method.POST) {
                connection.doOutput = true
                connection.outputStream.use { it.write(requestBody) }
            }

            val status = Response.Status.lookup(connection.responseCode) ?: Response.Status.OK
            val bodyBytes = if (session.method == Method.HEAD) {
                ByteArray(0)
            } else {
                val stream = try {
                    connection.inputStream
                } catch (_: IOException) {
                    connection.errorStream
                }
                stream?.use { it.readBytes() } ?: ByteArray(0)
            }
            val mime = connection.contentType?.substringBefore(';') ?: "application/json"
            val response = newChunkedResponse(status, mime, ByteArrayInputStream(bodyBytes))
            connection.headerFields
                .filterKeys { it != null }
                .forEach { (key, values) ->
                    values?.forEach { value -> response.addHeader(key, value) }
                }
            response.addHeader("Cache-Control", "no-store")
            response
        } catch (error: Exception) {
            if (bridgeKind == "lyricflow") {
                val fallback = handleLyricflowBridgeFallback(session, requestBody)
                if (fallback != null) {
                    Log.w(TAG, "LyricFlow backend unavailable, served local fallback for ${session.uri}", error)
                    return fallback
                }
            }
            Log.w(TAG, "Bridge proxy failure for $targetUrl", error)
            newFixedLengthResponse(
                Response.Status.lookup(502) ?: Response.Status.INTERNAL_ERROR,
                "text/plain",
                "502 Bridge proxy failed: ${error.message ?: "unknown"}"
            )
        }
    }

    private fun readRequestBody(session: IHTTPSession): ByteArray {
        val body = ByteArrayOutputStream()
        session.inputStream.use { input -> input.copyTo(body) }
        return body.toByteArray()
    }

    private fun handleLyricflowBridgeFallback(session: IHTTPSession, requestBody: ByteArray): Response? {
        val suffix = session.uri.removePrefix("${BRIDGE_PROXY_PREFIX}lyricflow")
        if (session.method != Method.POST) return null

        return when (suffix) {
            "/v1/lyricflow/initialize", "/v1/lyricflow/dispose" -> {
                newFixedLengthResponse(
                    Response.Status.OK,
                    "application/json",
                    JSONObject().put("ok", true).put("mode", "android-local-lrclib").toString()
                ).apply {
                    addHeader("Cache-Control", "no-store")
                }
            }
            "/v1/lyricflow/get-lyrics" -> {
                try {
                    val payload = JSONObject(String(requestBody, Charsets.UTF_8))
                    val songId = payload.optString("songId", "")
                    val result = fetchDirectLrcLibLyrics(songId)
                    newFixedLengthResponse(Response.Status.OK, "application/json", result.toString()).apply {
                        addHeader("Cache-Control", "no-store")
                    }
                } catch (error: Exception) {
                    Log.w(TAG, "LyricFlow local fallback failed", error)
                    newFixedLengthResponse(
                        Response.Status.lookup(502) ?: Response.Status.INTERNAL_ERROR,
                        "text/plain",
                        "502 LyricFlow local fallback failed: ${error.message ?: "unknown"}"
                    )
                }
            }
            else -> null
        }
    }

    private fun fetchDirectLrcLibLyrics(songId: String): JSONObject {
        val identity = parseSongIdentity(songId)
            ?: throw IOException("LRCLIB fallback could not parse song identity from \"$songId\"")

        try {
            val getRecord = fetchJsonObject(
                buildLrcLibUrl(
                    LRCLIB_GET_URL,
                    linkedMapOf(
                        "artist_name" to identity.artist,
                        "track_name" to identity.title,
                    )
                )
            )
            extractSyncedLyrics(getRecord)?.let { return it }
        } catch (error: IOException) {
            if (!(error.message ?: "").contains("404")) {
                throw error
            }
        }

        val searchRecord = fetchJsonArray(
            buildLrcLibUrl(
                LRCLIB_SEARCH_URL,
                linkedMapOf(
                    "artist_name" to identity.artist,
                    "track_name" to identity.title,
                )
            )
        )
        var picked = pickBestRecord(searchRecord, identity)
        if (picked == null && identity.artist.isNotBlank()) {
            val titleOnly = fetchJsonArray(
                buildLrcLibUrl(
                    LRCLIB_SEARCH_URL,
                    linkedMapOf("track_name" to identity.title)
                )
            )
            picked = pickBestRecord(titleOnly, identity)
        }

        return extractSyncedLyrics(picked)
            ?: throw IOException("LRCLIB fallback returned no synced lyrics for \"$songId\"")
    }

    private fun buildLrcLibUrl(baseUrl: String, params: Map<String, String>): String {
        val query = params.entries
            .filter { it.value.trim().isNotEmpty() }
            .joinToString("&") {
                "${URLEncoder.encode(it.key, "UTF-8")}=${URLEncoder.encode(it.value.trim(), "UTF-8")}"
            }
        return if (query.isEmpty()) baseUrl else "$baseUrl?$query"
    }

    private fun fetchJsonObject(url: String): JSONObject {
        val parsed = fetchJson(url)
        if (parsed is JSONObject) return parsed
        throw IOException("LRCLIB request returned invalid object payload")
    }

    private fun fetchJsonArray(url: String): JSONArray {
        val parsed = fetchJson(url)
        if (parsed is JSONArray) return parsed
        throw IOException("LRCLIB request returned invalid array payload")
    }

    private fun fetchJson(url: String): Any {
        val connection = (URL(url).openConnection() as HttpURLConnection).apply {
            requestMethod = "GET"
            instanceFollowRedirects = false
            connectTimeout = 4000
            readTimeout = 10000
            doInput = true
            setRequestProperty("Accept", "application/json")
            setRequestProperty("Cache-Control", "no-store")
            setRequestProperty("User-Agent", "AxolyncAndroidWrapper/1.0")
        }

        val status = connection.responseCode
        val stream = if (status in 200..299) connection.inputStream else connection.errorStream
        val body = stream?.bufferedReader()?.use { it.readText() } ?: ""
        if (status !in 200..299) {
            throw IOException("LRCLIB request failed: $status ${connection.responseMessage}".trim())
        }
        return JSONTokener(body).nextValue()
    }

    private fun parseSongIdentity(songId: String): SongIdentity? {
        val raw = normalizeLrcLibText(songId)
        if (raw.isEmpty()) return null

        listOf("::", " - ", " — ", "|", "/").forEach { separator ->
            if (!raw.contains(separator)) return@forEach
            val parts = raw.split(separator, limit = 2)
            if (parts.size != 2) return@forEach
            val artist = normalizeLrcLibText(parts[0])
            val title = normalizeLrcLibText(parts[1])
            if (artist.isNotEmpty() && title.isNotEmpty()) {
                return SongIdentity(artist, title)
            }
        }

        val colonParts = raw.split(':').map { normalizeLrcLibText(it) }.filter { it.isNotEmpty() }
        if (colonParts.size >= 3 && colonParts[0].contains('.')) {
            return SongIdentity(
                artist = normalizeLrcLibText(colonParts.drop(2).joinToString(":")),
                title = colonParts[1]
            )
        }
        if (colonParts.size == 2) {
            return SongIdentity(artist = colonParts[0], title = colonParts[1])
        }

        return null
    }

    private fun normalizeLrcLibText(value: String): String {
        return value.trim().replace(Regex("\\s+"), " ")
    }

    private fun pickBestRecord(rows: JSONArray, identity: SongIdentity): JSONObject? {
        val artist = identity.artist.lowercase()
        val title = identity.title.lowercase()
        var firstObject: JSONObject? = null
        for (index in 0 until rows.length()) {
            val row = rows.optJSONObject(index) ?: continue
            if (firstObject == null) firstObject = row
            val rowArtist = row.optString("artistName").trim().lowercase()
            val rowTitle = row.optString("trackName").trim().lowercase()
            if (rowArtist == artist && rowTitle == title) {
                return row
            }
        }
        return firstObject
    }

    private fun extractSyncedLyrics(record: JSONObject?): JSONObject? {
        val syncedLyrics = record?.optString("syncedLyrics")?.trim().orEmpty()
        if (syncedLyrics.isEmpty()) return null

        val entries = mutableListOf<Pair<Long, String>>()
        val pattern = Regex("^\\[([^\\]]+)](.*)$")
        syncedLyrics.split(Regex("\\r?\\n"))
            .map { it.trim() }
            .filter { it.isNotEmpty() }
            .forEach { line ->
                val match = pattern.find(line) ?: return@forEach
                val inSongMs = parseLrcTimestamp(match.groupValues[1]) ?: return@forEach
                val text = normalizeLrcLibText(match.groupValues[2])
                if (text.isNotEmpty()) {
                    entries += inSongMs to text
                }
            }

        if (entries.isEmpty()) return null

        val units = JSONArray()
        entries.forEachIndexed { index, entry ->
            val nextStart = entries.getOrNull(index + 1)?.first ?: (entry.first + 2500L)
            units.put(
                JSONObject()
                    .put("text", entry.second)
                    .put("inSongMs", entry.first)
                    .put("durationMs", maxOf(200L, nextStart - entry.first))
            )
        }
        return JSONObject()
            .put("granularity", "line")
            .put("units", units)
    }

    private fun parseLrcTimestamp(value: String): Long? {
        val match = Regex("^(\\d{2}):(\\d{2})(?:[.:](\\d{1,3}))?$").find(value) ?: return null
        val minutes = match.groupValues[1].toLongOrNull() ?: return null
        val seconds = match.groupValues[2].toLongOrNull() ?: return null
        val fractionRaw = match.groupValues.getOrElse(3) { "0" }.ifEmpty { "0" }
        val fractionMs = when (fractionRaw.length) {
            1 -> fractionRaw.toLong() * 100L
            2 -> fractionRaw.toLong() * 10L
            else -> fractionRaw.take(3).toLong()
        }
        return (minutes * 60_000L) + (seconds * 1000L) + fractionMs
    }

    private fun resolveAsset(uri: String): ResolvedAsset? {
        val candidates = linkedSetOf(uri)
        val lastSegment = uri.substringAfterLast('/')
        val hasExtension = lastSegment.contains('.')

        if (!hasExtension) {
            // TypeScript output in this project uses extensionless ESM imports.
            candidates.add("${uri}.js")
            candidates.add("${uri}.mjs")
            candidates.add("${uri}/index.js")
            candidates.add("${uri}/index.mjs")
            candidates.add("${uri}/index.html")
        }

        for (candidate in candidates) {
            val assetPath = "$assetBasePath$candidate"
            if (assetExists(assetPath)) {
                return ResolvedAsset(candidate, assetPath, getMimeType(candidate))
            }
        }

        return null
    }

    private fun assetExists(assetPath: String): Boolean {
        return try {
            assetManager.open(assetPath).use { /* existence check */ }
            true
        } catch (_: IOException) {
            false
        }
    }

    /**
     * Normalize URI and prevent path traversal attacks.
     * Returns null if traversal attempt detected.
     */
    private fun normalizeUri(uri: String): String? {
        // Decode URI
        val decoded = try {
            java.net.URLDecoder.decode(uri, "UTF-8")
        } catch (e: Exception) {
            return null
        }

        // Normalize multiple slashes to single slash
        val normalized = decoded.replace(Regex("/+"), "/")

        // Reject suspicious patterns after normalization
        if (normalized.contains("..")) {
            return null
        }
        if (normalized.contains("%2e%2e", ignoreCase = true) ||
            normalized.contains("%2f%2e%2e", ignoreCase = true)
        ) {
            return null
        }
        if (normalized.contains("\\")) {
            return null
        }
        if (normalized.contains("\u0000")) {
            return null
        }

        return normalized
    }

    /**
     * Determine if request should fallback to index.html for SPA routing.
     */
    private fun shouldFallbackToIndex(uri: String): Boolean {
        if (uri == "/health") return false
        if (uri.startsWith("/api/")) return false
        if (uri == BRIDGE_CONFIG_PATH) return false
        if (uri == BRIDGE_DEV_LOG_PATH) return false
        if (uri.startsWith(BRIDGE_PROXY_PREFIX)) return false

        // Don't fallback for internal static/module directories.
        if (uri.startsWith("/core/") ||
            uri.startsWith("/ui/") ||
            uri.startsWith("/plugins/") ||
            uri.startsWith("/workers/") ||
            uri.startsWith("/demo/")) {
            return false
        }

        val lastSegment = uri.substringAfterLast('/')
        if (lastSegment.contains('.')) return false

        return true
    }

    private fun getMimeType(uri: String): String {
        val extension = uri.substringAfterLast('.', "")
        return MIME_TYPES[".$extension"] ?: "application/octet-stream"
    }

    fun getServerUrl(): String {
        // Canonical URL uses localhost hostname.
        return "http://localhost:${listeningPort}"
    }

    fun isRunning(): Boolean {
        return isAlive
    }
}
