package com.axolync.android.server

import android.content.Context
import android.content.res.AssetManager
import android.util.Log
import com.axolync.android.logging.RuntimeNativeLogStore
import com.axolync.android.python.EmbeddedPythonManager
import com.axolync.android.python.EmbeddedPythonRuntimeStatus
import fi.iki.elonen.NanoHTTPD
import java.io.ByteArrayInputStream
import java.io.ByteArrayOutputStream
import java.io.IOException
import java.net.HttpURLConnection
import java.net.URL
import java.util.concurrent.Executors
import java.util.concurrent.TimeUnit
import java.util.concurrent.TimeoutException
import org.json.JSONObject

/**
 * LocalHttpServer serves bundled web application assets via HTTP on localhost.
 * Hardened with traversal protection, method restrictions, SPA fallback, and
 * support for extensionless ESM imports generated by TypeScript output.
 */
class LocalHttpServer(
    private val context: Context,
    private val port: Int = 0, // 0 = auto-assign
    private val runtimeBackendStatusProvider: () -> EmbeddedPythonRuntimeStatus = {
        EmbeddedPythonManager.getInstance(context).runSelfTest()
    },
    private val lyricflowBridgeInvoker: (String, String, String?) -> String = { operation, payloadJson, headersJson ->
        EmbeddedPythonManager.getInstance(context).invokeLyricFlowBridge(operation, payloadJson, headersJson)
    },
    private val lyricflowBridgeTimeoutMs: Long = 15_000L
) : NanoHTTPD("127.0.0.1", port) {

    private data class ResolvedAsset(val requestPath: String, val assetPath: String, val mimeType: String)

    private val assetManager: AssetManager = context.assets
    private val assetBasePath = "axolync-browser"

    companion object {
        private const val TAG = "LocalHttpServer"
        private const val BRIDGE_CONFIG_PATH = "/__axolync/runtime-bridge-config"
        private const val RUNTIME_BACKEND_STATUS_PATH = "/__axolync/runtime-backend-status"
        private const val RUNTIME_NATIVE_LOG_PATH = "/__axolync/runtime-native-log"
        private const val BRIDGE_PROXY_PREFIX = "/__axolync/bridge/"
        private const val BRIDGE_DEV_LOG_PATH = "/__axolync/dev-bridge-log"
        private const val BRIDGE_HOST = "localhost"
        private const val SONGSENSE_BACKEND_PORT = 8000
        private const val SYNCENGINE_BACKEND_PORT = 3000
        private const val LYRICFLOW_BACKEND_PORT = 8093
        // Supported MIME types (explicit mapping)
        private val MIME_TYPES = mapOf(
            ".html" to "text/html",
            ".js" to "application/javascript",
            ".mjs" to "application/javascript",
            ".ts" to "application/javascript",
            ".css" to "text/css",
            ".json" to "application/json",
            ".map" to "application/json",
            ".svg" to "image/svg+xml",
            ".png" to "image/png",
            ".jpg" to "image/jpeg",
            ".jpeg" to "image/jpeg",
            ".ogg" to "audio/ogg",
            ".mp3" to "audio/mpeg",
            ".wav" to "audio/wav",
            ".lrc" to "text/plain; charset=utf-8",
            ".woff" to "font/woff",
            ".woff2" to "font/woff2",
            ".ttf" to "font/ttf",
            ".wasm" to "application/wasm"
        )
        private val EMBEDDED_BRIDGE_EXECUTOR = Executors.newCachedThreadPool()
    }

    override fun serve(session: IHTTPSession): Response {
        if (session.uri == BRIDGE_CONFIG_PATH && (session.method == Method.GET || session.method == Method.HEAD)) {
            return serveRuntimeBridgeConfig(session)
        }

        if (session.uri == RUNTIME_BACKEND_STATUS_PATH && (session.method == Method.GET || session.method == Method.HEAD)) {
            return serveRuntimeBackendStatus(session)
        }

        if (session.uri == RUNTIME_NATIVE_LOG_PATH && (session.method == Method.GET || session.method == Method.HEAD)) {
            return serveRuntimeNativeLog(session)
        }

        if (session.uri == BRIDGE_DEV_LOG_PATH && session.method == Method.POST) {
            return handleBridgeDevLog(session)
        }

        val bridgeKind = resolveBridgeKind(session.uri)
        val bridgeTarget = resolveBridgeTargetUrl(session.uri)
        if (bridgeTarget != null && (session.method == Method.GET || session.method == Method.HEAD || session.method == Method.POST)) {
            return proxyBridgeRequest(session, bridgeTarget, bridgeKind)
        }

        // Only allow GET and HEAD methods
        if (session.method != Method.GET && session.method != Method.HEAD) {
            Log.w(TAG, "Method not allowed: ${session.method}")
            return newFixedLengthResponse(
                Response.Status.METHOD_NOT_ALLOWED,
                "text/plain",
                "405 Method Not Allowed"
            )
        }

        var uri = session.uri

        // Health check endpoint
        if (uri == "/health") {
            return newFixedLengthResponse(
                Response.Status.OK,
                "application/json",
                "{\"status\":\"ok\",\"server\":\"LocalHttpServer\",\"version\":\"1.0\"}"
            )
        }

        // Normalize URI FIRST, then check for traversal
        uri = normalizeUri(uri) ?: run {
            Log.w(TAG, "Path traversal attempt blocked: ${session.uri}")
            return newFixedLengthResponse(
                Response.Status.FORBIDDEN,
                "text/plain",
                "403 Forbidden"
            )
        }

        // Default to index.html for root
        if (uri == "/" || uri.isEmpty()) {
            uri = "/index.html"
        }

        val resolved = resolveAsset(uri)
        if (resolved != null) {
            if (session.method == Method.HEAD) {
                Log.d(TAG, "HEAD: ${resolved.assetPath} (${resolved.mimeType})")
                val response = newFixedLengthResponse(Response.Status.OK, resolved.mimeType, "")
                response.addHeader("Content-Type", resolved.mimeType)
                return response
            }

            return try {
                val inputStream = assetManager.open(resolved.assetPath)
                Log.d(TAG, "Serving: ${resolved.assetPath} (${resolved.mimeType})")
                newChunkedResponse(Response.Status.OK, resolved.mimeType, inputStream)
            } catch (e: IOException) {
                Log.w(TAG, "Failed to open resolved asset: ${resolved.assetPath}")
                newFixedLengthResponse(Response.Status.NOT_FOUND, "text/plain", "404 Not Found: $uri")
            }
        }

        // SPA fallback for extensionless app routes.
        if (shouldFallbackToIndex(uri)) {
            Log.d(TAG, "SPA fallback: serving index.html for $uri")
            return try {
                if (session.method == Method.HEAD) {
                    val response = newFixedLengthResponse(Response.Status.OK, "text/html", "")
                    response.addHeader("Content-Type", "text/html")
                    response
                } else {
                    val indexStream = assetManager.open("$assetBasePath/index.html")
                    newChunkedResponse(Response.Status.OK, "text/html", indexStream)
                }
            } catch (indexError: IOException) {
                Log.e(TAG, "Failed to serve index.html fallback", indexError)
                newFixedLengthResponse(Response.Status.NOT_FOUND, "text/plain", "404 Not Found: $uri")
            }
        }

        Log.w(TAG, "Asset not found after resolution: $uri")
        return newFixedLengthResponse(Response.Status.NOT_FOUND, "text/plain", "404 Not Found: $uri")
    }

    private fun serveRuntimeBridgeConfig(session: IHTTPSession): Response {
        val payload = """
            {
              "host": "localhost",
              "ports": {
                "host": "localhost",
                "browserDevPort": ${listeningPort},
                "desktopDevPort": 4173,
                "songsenseBackendPort": $SONGSENSE_BACKEND_PORT,
                "syncengineBackendPort": $SYNCENGINE_BACKEND_PORT,
                "lyricflowBackendPort": $LYRICFLOW_BACKEND_PORT
              },
              "baseUrls": {
                "songsense": "/__axolync/bridge/songsense/",
                "syncengine": "/__axolync/bridge/syncengine/",
                "lyricflow": "/__axolync/bridge/lyricflow/"
              },
              "backendUrls": {
                "songsense": "http://$BRIDGE_HOST:$SONGSENSE_BACKEND_PORT",
                "syncengine": "http://$BRIDGE_HOST:$SYNCENGINE_BACKEND_PORT",
                "lyricflow": "http://$BRIDGE_HOST:$LYRICFLOW_BACKEND_PORT"
              },
              "devLogEndpoint": "$BRIDGE_DEV_LOG_PATH"
            }
        """.trimIndent()
        val response = if (session.method == Method.HEAD) {
            newFixedLengthResponse(Response.Status.OK, "application/json", "")
        } else {
            newFixedLengthResponse(Response.Status.OK, "application/json", payload)
        }
        response.addHeader("Content-Type", "application/json")
        response.addHeader("Cache-Control", "no-store")
        return response
    }

    private fun serveRuntimeBackendStatus(session: IHTTPSession): Response {
        val lyricflowRuntimeStatus = runtimeBackendStatusProvider()
        val lyricflowPythonProcessSupported = true
        if (lyricflowRuntimeStatus.health == "ok") {
            Log.i(
                TAG,
                "Embedded Python runtime backend status healthy attempted=${lyricflowRuntimeStatus.startupAttempted} reused=${lyricflowRuntimeStatus.reusedExistingRuntime}"
            )
        } else {
            Log.e(
                TAG,
                "Embedded Python runtime backend status unhealthy stage=${lyricflowRuntimeStatus.startupFailureStage} message=${lyricflowRuntimeStatus.startupFailureMessage}"
            )
        }
        val payload = """
            {
              "runtime": "android-wrapper",
              "lyricflow": {
                "pythonProcessSupported": $lyricflowPythonProcessSupported,
                "launchAttempted": ${lyricflowRuntimeStatus.startupAttempted},
                "launchSucceeded": ${lyricflowRuntimeStatus.startupSucceeded},
                "startupFailureStage": ${JSONObject.quote(lyricflowRuntimeStatus.startupFailureStage)},
                "startupFailureMessage": ${JSONObject.quote(lyricflowRuntimeStatus.startupFailureMessage)},
                "criticalImportsSucceeded": ${lyricflowRuntimeStatus.criticalImportsSucceeded ?: JSONObject.NULL},
                "healthCheckSucceeded": ${lyricflowRuntimeStatus.healthCheckSucceeded ?: JSONObject.NULL},
                "health": ${JSONObject.quote(lyricflowRuntimeStatus.health)},
                "executionMode": "android-embedded-python"
              }
            }
        """.trimIndent()
        val response = if (session.method == Method.HEAD) {
            newFixedLengthResponse(Response.Status.OK, "application/json", "")
        } else {
            newFixedLengthResponse(Response.Status.OK, "application/json", payload)
        }
        response.addHeader("Content-Type", "application/json")
        response.addHeader("Cache-Control", "no-store")
        return response
    }

    private fun handleBridgeDevLog(session: IHTTPSession): Response {
        return try {
            val payload = readRequestBody(session)
            Log.d(TAG, "Bridge dev log payload bytes=${payload.size}")
            newFixedLengthResponse(Response.Status.NO_CONTENT, "text/plain", "")
        } catch (error: Exception) {
            Log.w(TAG, "Failed to record bridge dev log", error)
            newFixedLengthResponse(Response.Status.INTERNAL_ERROR, "text/plain", "500 Failed to record bridge log")
        }
    }

    private fun serveRuntimeNativeLog(session: IHTTPSession): Response {
        val payload = JSONObject()
            .put("generatedAtMs", System.currentTimeMillis())
            .put("entries", RuntimeNativeLogStore.toJsonArray())
            .toString()
        val response = if (session.method == Method.HEAD) {
            newFixedLengthResponse(Response.Status.OK, "application/json", "")
        } else {
            newFixedLengthResponse(Response.Status.OK, "application/json", payload)
        }
        response.addHeader("Content-Type", "application/json")
        response.addHeader("Cache-Control", "no-store")
        return response
    }

    private fun resolveBridgeKind(uri: String): String? {
        if (!uri.startsWith(BRIDGE_PROXY_PREFIX)) return null
        val remainder = uri.removePrefix(BRIDGE_PROXY_PREFIX)
        val slashIndex = remainder.indexOf('/')
        return if (slashIndex >= 0) remainder.substring(0, slashIndex) else remainder
    }

    private fun resolveBridgeTargetUrl(uri: String): String? {
        val kind = resolveBridgeKind(uri) ?: return null
        val remainder = uri.removePrefix(BRIDGE_PROXY_PREFIX)
        val slashIndex = remainder.indexOf('/')
        val suffix = if (slashIndex >= 0) remainder.substring(slashIndex) else "/"
        val port = when (kind) {
            "songsense" -> SONGSENSE_BACKEND_PORT
            "syncengine" -> SYNCENGINE_BACKEND_PORT
            "lyricflow" -> LYRICFLOW_BACKEND_PORT
            else -> return null
        }
        return "http://$BRIDGE_HOST:$port$suffix"
    }

    private fun proxyBridgeRequest(session: IHTTPSession, targetUrl: String, bridgeKind: String?): Response {
        val requestBody = if (session.method == Method.POST) readRequestBody(session) else ByteArray(0)
        if (bridgeKind == "lyricflow") {
            val embeddedResponse = handleEmbeddedLyricflowBridgeRequest(session, requestBody)
            if (embeddedResponse != null) {
                return embeddedResponse
            }
        }
        return try {
            val connection = (URL(targetUrl).openConnection() as HttpURLConnection).apply {
                requestMethod = session.method.name
                instanceFollowRedirects = false
                connectTimeout = 3000
                readTimeout = 10_000
                doInput = true
                setRequestProperty("Accept", "application/json")
                setRequestProperty("Cache-Control", "no-store")
                for ((key, value) in session.headers) {
                    if (key.equals("content-length", ignoreCase = true)) continue
                    if (key.equals("host", ignoreCase = true)) continue
                    if (key.equals("connection", ignoreCase = true)) continue
                    setRequestProperty(key, value)
                }
            }

            if (session.method == Method.POST) {
                connection.doOutput = true
                connection.outputStream.use { it.write(requestBody) }
            }

            val status = Response.Status.lookup(connection.responseCode) ?: Response.Status.OK
            val bodyBytes = if (session.method == Method.HEAD) {
                ByteArray(0)
            } else {
                val stream = try {
                    connection.inputStream
                } catch (_: IOException) {
                    connection.errorStream
                }
                stream?.use { it.readBytes() } ?: ByteArray(0)
            }
            val mime = connection.contentType?.substringBefore(';') ?: "application/json"
            val response = newChunkedResponse(status, mime, ByteArrayInputStream(bodyBytes))
            connection.headerFields
                .filterKeys { it != null }
                .forEach { (key, values) ->
                    values?.forEach { value -> response.addHeader(key, value) }
                }
            response.addHeader("Cache-Control", "no-store")
            response
        } catch (error: Exception) {
            Log.w(TAG, "Bridge proxy failure for $targetUrl", error)
            newFixedLengthResponse(
                Response.Status.lookup(502) ?: Response.Status.INTERNAL_ERROR,
                "text/plain",
                "502 Bridge proxy failed: ${error.message ?: "unknown"}"
            )
        }
    }

    private fun readRequestBody(session: IHTTPSession): ByteArray {
        RuntimeNativeLogStore.record(TAG, "info", "Reading local bridge POST body", "uri=${session.uri}")
        val files = linkedMapOf<String, String>()
        try {
            session.parseBody(files)
            val postData = files["postData"]
            if (postData != null) {
                val bytes = postData.toByteArray(Charsets.UTF_8)
                RuntimeNativeLogStore.record(
                    TAG,
                    "info",
                    "Read local bridge POST body from NanoHTTPD parseBody",
                    "uri=${session.uri} bytes=${bytes.size}"
                )
                return bytes
            }
        } catch (error: Exception) {
            RuntimeNativeLogStore.record(
                TAG,
                "error",
                "NanoHTTPD parseBody failed for local bridge POST",
                "uri=${session.uri} error=${error.message ?: error.javaClass.simpleName}"
            )
        }

        val declaredLength = session.headers["content-length"]?.toIntOrNull()
        if (declaredLength != null && declaredLength >= 0) {
            val bytes = session.inputStream.readNBytes(declaredLength)
            RuntimeNativeLogStore.record(
                TAG,
                "info",
                "Read local bridge POST body using bounded fallback",
                "uri=${session.uri} declaredBytes=$declaredLength actualBytes=${bytes.size}"
            )
            return bytes
        }

        val body = ByteArrayOutputStream()
        session.inputStream.use { input -> input.copyTo(body) }
        val bytes = body.toByteArray()
        RuntimeNativeLogStore.record(
            TAG,
            "warn",
            "Read local bridge POST body using EOF fallback",
            "uri=${session.uri} bytes=${bytes.size}"
        )
        return bytes
    }

    private fun handleEmbeddedLyricflowBridgeRequest(session: IHTTPSession, requestBody: ByteArray): Response? {
        val suffix = session.uri.removePrefix("${BRIDGE_PROXY_PREFIX}lyricflow")
        if (session.method != Method.POST) return null
        val operation = when (suffix) {
            "/v1/lyricflow/initialize" -> "initialize_session"
            "/v1/lyricflow/get-lyrics" -> "get_lyrics"
            "/v1/lyricflow/dispose" -> "dispose_session"
            else -> return null
        }

        val runtimeStatus = runtimeBackendStatusProvider()
        if (!runtimeStatus.startupSucceeded || runtimeStatus.health != "ok") {
            Log.e(
                TAG,
                "Embedded LyricFlow bridge request blocked by unhealthy Python runtime stage=${runtimeStatus.startupFailureStage} message=${runtimeStatus.startupFailureMessage}"
            )
            RuntimeNativeLogStore.record(
                TAG,
                "error",
                "Embedded LyricFlow bridge request blocked by unhealthy runtime",
                "operation=$operation stage=${runtimeStatus.startupFailureStage ?: "unknown"} message=${runtimeStatus.startupFailureMessage ?: "unknown"}"
            )
            val errorPayload = JSONObject()
                .put("code", "PROVIDER_UNAVAILABLE")
                .put("message", "Embedded Python runtime unavailable for LyricFlow")
                .put("retryable", false)
                .put(
                    "details",
                    JSONObject()
                        .put("startupFailureStage", runtimeStatus.startupFailureStage ?: JSONObject.NULL)
                        .put("startupFailureMessage", runtimeStatus.startupFailureMessage ?: JSONObject.NULL)
                        .put("health", runtimeStatus.health)
                )
            return newFixedLengthResponse(
                Response.Status.lookup(502) ?: Response.Status.INTERNAL_ERROR,
                "application/json",
                errorPayload.toString()
            ).apply {
                addHeader("Cache-Control", "no-store")
            }
        }
        val requestStartedAtMs = System.currentTimeMillis()
        RuntimeNativeLogStore.record(
            TAG,
            "info",
            "Embedded LyricFlow bridge request started",
            "operation=$operation bytes=${requestBody.size}"
        )
        return try {
            val responseJson = invokeEmbeddedLyricflowBridgeWithTimeout(operation, requestBody, session.headers)
            val elapsedMs = System.currentTimeMillis() - requestStartedAtMs
            RuntimeNativeLogStore.record(
                TAG,
                "info",
                "Embedded LyricFlow bridge request succeeded",
                "operation=$operation elapsedMs=$elapsedMs"
            )
            newFixedLengthResponse(Response.Status.OK, "application/json", responseJson).apply {
                addHeader("Cache-Control", "no-store")
            }
        } catch (error: TimeoutException) {
            val elapsedMs = System.currentTimeMillis() - requestStartedAtMs
            RuntimeNativeLogStore.record(
                TAG,
                "error",
                "Embedded LyricFlow bridge request timed out",
                "operation=$operation elapsedMs=$elapsedMs timeoutMs=$lyricflowBridgeTimeoutMs"
            )
            val errorPayload = JSONObject()
                .put("code", "BRIDGE_TIMEOUT")
                .put("message", "Embedded LyricFlow bridge request timed out")
                .put("retryable", true)
                .put(
                    "details",
                    JSONObject()
                        .put("operation", operation)
                        .put("timeoutMs", lyricflowBridgeTimeoutMs)
                        .put("elapsedMs", elapsedMs)
                )
            newFixedLengthResponse(
                Response.Status.lookup(504) ?: Response.Status.INTERNAL_ERROR,
                "application/json",
                errorPayload.toString()
            ).apply {
                addHeader("Cache-Control", "no-store")
            }
        } catch (error: Exception) {
            val elapsedMs = System.currentTimeMillis() - requestStartedAtMs
            Log.e(TAG, "Embedded LyricFlow bridge invocation failed for $suffix", error)
            RuntimeNativeLogStore.record(
                TAG,
                "error",
                "Embedded LyricFlow bridge request failed",
                "operation=$operation elapsedMs=$elapsedMs error=${error.message ?: error.javaClass.simpleName}"
            )
            val errorPayload = JSONObject()
                .put("code", "BRIDGE_INVOCATION_FAILED")
                .put("message", "Embedded LyricFlow bridge invocation failed")
                .put("retryable", false)
                .put(
                    "details",
                    JSONObject()
                        .put("operation", operation)
                        .put("elapsedMs", elapsedMs)
                        .put("error", error.message ?: error.javaClass.simpleName)
                )
            newFixedLengthResponse(
                Response.Status.lookup(502) ?: Response.Status.INTERNAL_ERROR,
                "application/json",
                errorPayload.toString()
            ).apply {
                addHeader("Cache-Control", "no-store")
            }
        }
    }

    private fun invokeEmbeddedLyricflowBridgeWithTimeout(
        operation: String,
        requestBody: ByteArray,
        headers: Map<String, String>
    ): String {
        val task = EMBEDDED_BRIDGE_EXECUTOR.submit<String> {
            invokeEmbeddedLyricflowBridge(operation, requestBody, headers)
        }
        return try {
            task.get(lyricflowBridgeTimeoutMs, TimeUnit.MILLISECONDS)
        } catch (error: TimeoutException) {
            task.cancel(true)
            throw error
        }
    }

    private fun invokeEmbeddedLyricflowBridge(
        operation: String,
        requestBody: ByteArray,
        headers: Map<String, String>
    ): String {
        val payloadJson = String(requestBody, Charsets.UTF_8)
        val headerJson = JSONObject().apply {
            headers.forEach { (key, value) ->
                if (!key.equals("content-length", ignoreCase = true) &&
                    !key.equals("host", ignoreCase = true) &&
                    !key.equals("connection", ignoreCase = true)
                ) {
                    put(key, value)
                }
            }
        }.toString()
        return lyricflowBridgeInvoker(operation, payloadJson, headerJson)
    }

    private fun resolveAsset(uri: String): ResolvedAsset? {
        val candidates = linkedSetOf(uri)
        val lastSegment = uri.substringAfterLast('/')
        val hasExtension = lastSegment.contains('.')

        if (!hasExtension) {
            // TypeScript output in this project uses extensionless ESM imports.
            candidates.add("${uri}.js")
            candidates.add("${uri}.mjs")
            candidates.add("${uri}/index.js")
            candidates.add("${uri}/index.mjs")
            candidates.add("${uri}/index.html")
        }

        for (candidate in candidates) {
            val assetPath = "$assetBasePath$candidate"
            if (assetExists(assetPath)) {
                return ResolvedAsset(candidate, assetPath, getMimeType(candidate))
            }
        }

        return null
    }

    private fun assetExists(assetPath: String): Boolean {
        return try {
            assetManager.open(assetPath).use { /* existence check */ }
            true
        } catch (_: IOException) {
            false
        }
    }

    /**
     * Normalize URI and prevent path traversal attacks.
     * Returns null if traversal attempt detected.
     */
    private fun normalizeUri(uri: String): String? {
        // Decode URI
        val decoded = try {
            java.net.URLDecoder.decode(uri, "UTF-8")
        } catch (e: Exception) {
            return null
        }

        // Normalize multiple slashes to single slash
        val normalized = decoded.replace(Regex("/+"), "/")

        // Reject suspicious patterns after normalization
        if (normalized.contains("..")) {
            return null
        }
        if (normalized.contains("%2e%2e", ignoreCase = true) ||
            normalized.contains("%2f%2e%2e", ignoreCase = true)
        ) {
            return null
        }
        if (normalized.contains("\\")) {
            return null
        }
        if (normalized.contains("\u0000")) {
            return null
        }

        return normalized
    }

    /**
     * Determine if request should fallback to index.html for SPA routing.
     */
    private fun shouldFallbackToIndex(uri: String): Boolean {
        if (uri == "/health") return false
        if (uri.startsWith("/api/")) return false
        if (uri == BRIDGE_CONFIG_PATH) return false
        if (uri == BRIDGE_DEV_LOG_PATH) return false
        if (uri.startsWith(BRIDGE_PROXY_PREFIX)) return false

        // Don't fallback for internal static/module directories.
        if (uri.startsWith("/core/") ||
            uri.startsWith("/ui/") ||
            uri.startsWith("/plugins/") ||
            uri.startsWith("/workers/") ||
            uri.startsWith("/demo/")) {
            return false
        }

        val lastSegment = uri.substringAfterLast('/')
        if (lastSegment.contains('.')) return false

        return true
    }

    private fun getMimeType(uri: String): String {
        val extension = uri.substringAfterLast('.', "")
        return MIME_TYPES[".$extension"] ?: "application/octet-stream"
    }

    fun getServerUrl(): String {
        // Canonical URL uses localhost hostname.
        return "http://localhost:${listeningPort}"
    }

    fun isRunning(): Boolean {
        return isAlive
    }
}
